[package]
name = "treesitter_nif"
version = "0.1.0"
edition = "2021"

[lib]
name = "treesitter_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.37"
tree-sitter = "0.24"
tree-sitter-language = "0.1"
tree-sitter-elixir = "0.3"
tree-sitter-heex = "0.8"
